# WARNING: This is a CI docker-compose file used for building and testing of the entire app, it should not be used for production.
services:

  fullstack:
    environment:
      DB_ENGINE: 'mysql'
      DB_HOST: 'db-mysql'
      DB_PORT: '3306'
      DB_NAME: 'npm'
      DB_USER: 'npm'
      DB_PASSWORD: 'npmpass'
    depends_on:
      - db-mysql

  db-mysql:
    image: jc21/mariadb-aria
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npmpass'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - mysql_vol:/var/lib/mysql
    networks:
      - fulltest

volumes:
  mysql_vol:
