name: Format Caddyfile
on:
  push:
    branches:
      - develop
    paths:
      - .github/workflows/caddy-fmt.yml
      - global/caddy/Dockerfile
      - global/caddy/Caddyfile
  workflow_dispatch:
jobs:
  caddy-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Read version
        id: version
        run: echo "version=$(cat global/caddy/Dockerfile | grep "^COPY --from=caddy:.*$" | head -1 | sed "s|COPY --from=caddy:\([0-9.]\+\).*|\1|g")" >> $GITHUB_OUTPUT
      - name: caddy-fmt
        run: |
          docker run --rm -v ${{ github.workspace }}/global/caddy/Caddyfile:/etc/caddy/Caddyfile caddy:${{ steps.version.outputs.version }} caddy fmt --overwrite /etc/caddy/Caddyfile
      - name: push changes
        run: |
          git add global/caddy/Caddyfile
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git diff-index --quiet HEAD || git commit -sm "caddy fmt"
          git push
